### ISSUE TITLE
Question about multiple losses

### ISSUE THREAD

**Issue by vadimkantorov** [ppengtang/oicr#5]
Hi!

Thanks for making the code available! I have a few minor questions:

1. Do I understand correctly that iterative retraining procedure is not performed and the refinement is implemented by combining `L_b` (`loss_midn`) and `L_r` (`loss_oicr`)?

2. Could you please comment on differences and purpose of `loss_oicr`, `loss_oicr1`, `loss_oicr2` loss combination? Do they represent iterative refinement in some way? Are the results of using only `loss_oicr` represented in Figure 4 at tick "1 refinement time"?

Thanks a lot!

**Comment by ppengtang** [comment]
Hi!
Thanks for your interest of our work.

The answers are as follows:
1. We don't provide codes about the alternatively training. The end-to-end jointly training codes are provided (combining L_b (loss_midn) and L_r (loss_oicr)).
2. The "loss_oicr", "loss_oicr1", and "loss_oicr2" indicate the 1, 2, 3 refinement time in Figure 4. We use the "loss_oicr", "loss_oicr1", and "loss_oicr2" to iteratively refine detectors online (instead of the time-consuming alternative training).

Feel free to contact me if there is any other question.

**Comment by vadimkantorov** [comment]
It's now clear. Thanks for your answers!
